### ISSUE TITLE
Create blank slate / templated backend

### ISSUE THREAD

**Issue by awesomeaiden** [lanterndevs/Lantern-Server#3]
Set up a very basic backend API using the agreed-upon languages/technologies. Implement placeholders for a few of the simpler endpoints.  Pick a popular and well-supported automated testing framework (could be something built-in to Node/Express or at least easy to add) and write a few basic tests to get us started!

**Comment by awesomeaiden** [comment]
One potential option for this is to use an OpenAPI generator such as https://github.com/OpenAPITools/openapi-generator.  This has pros and cons - main con I've seen is it can introduce some additional complexity and be difficult to get to work just right at first.

**Comment by Shibi-bala** [comment]
Built Express.js and mongoClient skeleton.
