### ISSUE TITLE
Create simple backend CI/CD pipeline

### ISSUE THREAD

**Issue by awesomeaiden** [lanterndevs/Lantern-Server#4]
Using GitHub actions or any other preferred platform (same platform as used the client), create basic CI/CD pipeline that we can add onto later. For a good start it should probably include:

- Running the automated testing
- Deploying to dev/testing version on selected cloud platform upon passing tests (or maybe upon manual approval?)

The pipeline can be activated upon a variety of actions - personally I think pull requests is a good choice but whatever works best.

**Comment by RishiKumarRay** [comment]
Where is the application, for which we have to make CI/CD?

**Comment by lanterndevs** [comment]
Hi Rishi, this project is currently in its beginning stages and is part of a university project.  As such its not open to outside contributions at this time, but thank you for your interest :)

**Comment by awesomeaiden** [comment]
Will create simple pipeline to attempt to test with chai framework and deploy to AWS EC2

**Comment by awesomeaiden** [comment]
Backend pipeline and manual deployment finished
